version: '2'

services:
  lb:
    image: dockercloud/haproxy
    environment:
      - VIRTUAL_HOST=git.example.com
      - VIRTUAL_NETWORK=frontend
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=git.example.com
      - LETSENCRYPT_EMAIL=hi@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - bitbucket
    links:
      - bitbucket
    networks:
      - frontend
      - backend
    restart: always

  bitbucket:
    image: dweomer/atlassian-bitbucket
    environment:
      EXCLUDE_PORTS: 7999
      BITBUCKET_CONNECTOR_PROXY_NAME: git.example.com
    domainname: example.com
    hostname: git
    volumes:
      - files:/var/lib/bitbucket
      - ./bitbucket.properties:/var/atlassian/application-data/bitbucket:ro
    links:
      - postgres:db
    networks:
      - backend
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

volumes:
  database:
    driver: local
  files:
    driver: local

networks:
  frontend:
    external:
      name: frontend
  backend:
    external:
      name: backend
